defaults:
  - _self_
  - model: unet3d   
  - satellite: s2  
  - experiment: exp1 

base_dir: "/dss/dsstbyfs02/pn49cu/pn49cu-dss-0006/Sen12Landslides"

dataset_type: "final" # or raw

train:
  gpus: 4
  precision: 16
  max_epochs: 50
  batch_size: 4
  output_dir: "${base_dir}/results/${model.name}_${experiment.name}_${satellite.name}_${experiment.variant}"
  log_dir: "${base_dir}/results/logs/${model.name}_${experiment.name}_${satellite.name}_${experiment.variant}"

hydra:
  job:
    chdir: false 

preprocess:
  test_size: 0.2
  val_size: 0.2
  seed: 42
