model:
  _target_: src.models.BiConvRNN.convgru.ConvGRU_Seg
  img_res: ${dataset.patch_size}
  timeseries_len: ${dataset.patch_length}
  num_channels: ${dataset.patch_channels}
  num_classes: 2
  shape: 'NCTHW'