name: unet3d
model:
  _target_: src.models.UNet3D.unet3d.UNet3D
  timeseries_len: ${dataset.input_length}
  num_channels: ${adjust_channels:${dataset.input_channels}, ${experiment.variant}}
  num_classes: 2
  dropout: 0.0