_target_: src.models.lit_module.Sen12LsLitModule

name: convlstm

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.convlstm.BConvLSTM_Seg
  num_classes: 2
  input_size: ${dataset.patch_size}
  input_dim: ${adjust_channels:${dataset.patch_channels}, ${experiment.variant}}   
  hidden_dim: 64      
  kernel_size: [3,3]
  pad_value: 0

compile: False