_target_: src.models.lit_module.Sen12LsLitModule

name: fpn_convlstm

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.fpn_convlstm.FPNConvLSTM
  input_dim: ${adjust_channels:${dataset.patch_channels}, ${experiment.variant}} 
  num_classes: 2
  inconv: [32, 64]
  n_levels: 5
  n_channels: 64
  hidden_size: 88
  input_shape: [128, 128]
  mid_conv: true
  pad_value: 0

compile: False