_target_: src.models.lit_module.Sen12LsLitModule

name: stamnet

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.stamnet.STAMNet
  hidden_dim: 256
  kernel_size: 3
  num_layers: 2
  num_classes: 2
  in_channels: 11
  image_res: 128
  patch_size: 16

compile: False
