_target_: src.models.lit_module.Sen12LsLitModule

name: stvit

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.vit.STViT
  img_res: 32
  timeseries_len: ${dataset.patch_length}       
  num_channels: ${adjust_channels:${dataset.patch_channels}, ${experiment.variant}}
  patch_size: 2                         # size of each patch (adjust as needed)
  num_classes: 2                         # number of segmentation classes
  dim: 512                               # embedding dimension for patches
  depth: 3                               # number of transformer layers
  heads: 4                               # number of attention heads
  dim_head: 16                           # dimension per head
  dropout: 0.                          # dropout probability in transformer layers
  emb_dropout: 0.                       # dropout probability for patch embeddings
  pool: "cls"                            # pooling type: "cls" token or "mean"
  scale_dim: 4                           # scale factor (adjust as needed)

compile: False
