name: unet2d_clstm
model:
  _target_: src.models.UNet2D_CLSTM.CropTypeMapping.models.FCN_CRNN
  train_stage: 2
  img_res: ${dataset.patch_size}
  timeseries_len: ${dataset.patch_length}
  num_channels: 2
  num_classes: 2
  attn_channels: 0
  cscl_win_size: 0
  cscl_win_dilation: 0
  cscl_win_stride: 0
  attn_groups: 0