_target_: lightning.pytorch.callbacks.ModelCheckpoint
dirpath: ${hydra:run.dir}/checkpoints                
filename: "{epoch}-{val_loss:.4f}"                
monitor: "val_loss"                 
verbose: False                
save_last: null               
save_top_k: 1                 
mode: "min"                   
auto_insert_metric_name: True 
save_weights_only: False      
every_n_train_steps: null     
train_time_interval: null     
every_n_epochs: null          
save_on_train_epoch_end: null 